version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: group_finder_db
    environment:
      MYSQL_DATABASE: groupfinder
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    container_name: group_finder_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/groupfinder
      DB_USER: root
      DB_PASSWORD: secret
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      JWT_SECRET: mysecret
      JWT_EXPIRATION: 3600

#volumes:
    #db_data:   if need persistent Db when compose up/down